### ISSUE TITLE
Incompatible with nixpkgs-unstable: unexpected argument 'self'

### ISSUE THREAD

**Issue by antifuchs** [nix-community/pip2nix#62]
Hey folks, pip2nix looks really promising! I tried running `nix-shell release.nix -A pip2nix.python36` on the unstable channel, and got this error:

```
error: while evaluating the attribute 'python36' at /Users/asf/Mess/Mess/pip2nix/release.nix:9:5:
while evaluating anonymous function at /Users/asf/Mess/Mess/pip2nix/default.nix:1:1, called from /Users/asf/Mess/Mess/pip2nix/release.nix:9:13:
while evaluating 'fix' at /nix/store/83wbkzydv8bfqhln7n1yivcqh1x7j0j5-nixpkgs-21.03pre266397.9b7e9dc6111/nixpkgs/lib/fixed-points.nix:19:9, called from /Users/asf/Mess/Mess/pip2nix/default.nix:67:6:
while evaluating 'extends' at /nix/store/83wbkzydv8bfqhln7n1yivcqh1x7j0j5-nixpkgs-21.03pre266397.9b7e9dc6111/nixpkgs/lib/fixed-points.nix:69:24, called from /nix/store/83wbkzydv8bfqhln7n1yivcqh1x7j0j5-nixpkgs-21.03pre266397.9b7e9dc6111/nixpkgs/lib/fixed-points.nix:19:20:
while evaluating 'extends' at /nix/store/83wbkzydv8bfqhln7n1yivcqh1x7j0j5-nixpkgs-21.03pre266397.9b7e9dc6111/nixpkgs/lib/fixed-points.nix:69:24, called from /nix/store/83wbkzydv8bfqhln7n1yivcqh1x7j0j5-nixpkgs-21.03pre266397.9b7e9dc6111/nixpkgs/lib/fixed-points.nix:69:42:
while evaluating anonymous function at /Users/asf/Mess/Mess/pip2nix/default.nix:14:5, called from /nix/store/83wbkzydv8bfqhln7n1yivcqh1x7j0j5-nixpkgs-21.03pre266397.9b7e9dc6111/nixpkgs/lib/fixed-points.nix:69:42:
while evaluating anonymous function at /nix/store/83wbkzydv8bfqhln7n1yivcqh1x7j0j5-nixpkgs-21.03pre266397.9b7e9dc6111/nixpkgs/lib/customisation.nix:77:32, called from /Users/asf/Mess/Mess/pip2nix/default.nix:14:11:
while evaluating 'makeOverridable' at /nix/store/83wbkzydv8bfqhln7n1yivcqh1x7j0j5-nixpkgs-21.03pre266397.9b7e9dc6111/nixpkgs/lib/customisation.nix:67:24, called from /nix/store/83wbkzydv8bfqhln7n1yivcqh1x7j0j5-nixpkgs-21.03pre266397.9b7e9dc6111/nixpkgs/lib/customisation.nix:77:41:
anonymous function at /nix/store/83wbkzydv8bfqhln7n1yivcqh1x7j0j5-nixpkgs-21.03pre266397.9b7e9dc6111/nixpkgs/pkgs/development/interpreters/python/default.nix:25:10 called with unexpected argument 'self', at /nix/store/83wbkzydv8bfqhln7n1yivcqh1x7j0j5-nixpkgs-21.03pre266397.9b7e9dc6111/nixpkgs/lib/customisation.nix:69:16
```

Running the command above on the `nixos-20.09-darwin` channel does work, however.

I suspect that something in python changed incompatibly from the previous release - hope this report is useful (:

**Comment by datakurre** [comment]
@antifuchs Thanks for the report. This was expected. pip2nix relies on pip internal API which used to be ”public” years ago, but was made internal to allow major refactoring in pip. As long as this is the case, it is practically impossible to support pip2nix outside releases, which freeze pip version.

Nowadays I use niv to manage environments and use pip2nix to generate packageset with 20.09 but then may use the packageset with unstable. So, release nixpkgs version is only required for running pip2nix and the resulting package set should work with unstable.

**Comment by antifuchs** [comment]
Thanks, I went down that route and could generate a python-packages.nix expression.

**Comment by rihardsk** [comment]
@datakurre could you please expand a bit on your proposed workaround?

I'm facing this issue currently as i'm trying to make two of my existing projects (the generated expressions for Python packages worked fine some 6 months earlier) work with the latest `nixpkgs`. The `default.nix` scaffolds in both of the projects were generated with `pip2nix 0.8.0.dev1`.

This seems to be the failing bit, btw
```python
basePythonPackagesUnfix = basePythonPackages.__unfix__ or (                                                                                                             
    self: basePythonPackages.override (a: { inherit self; }));   # <---
```
Aparently, `basePythonPackages` no longer accept a `self` attribute.

If i understood correctly, you propose that 1) `pip2nix` should be taken from the 20.09 packageset because of incompatibilities with `pip` in later versions. And then 2) the generated expressions for python packages could be used with the latest `nixpkgs`. In my case i don't need 1), because i already have the generated python package expressions, but 2) is failing with the reported error. I checked that there haven't been any changes in the default.nix scaffold that would solve the crash https://github.com/nix-community/pip2nix/blob/fb441b63eb92a237aadf644c70663fd089f8f41b/pip2nix/default.nix.j2#L16

EDIT: should have read the issue description more carefully. The posted stacktrace was for invoking pip2nix. Though, the last few lines of the stacktrace match with what i get when i'm trying to use the generated `default.nix` in my projects. So to me it seems that the same incompatibility with `basePythonPackages` is at fault in both cases.

**Comment by datakurre** [comment]
@rihardsk Wow. That scaffold is really old. Should find courage to update it :see_no_evil: 

There have been various alternatives in the recent closed issues. This is probably the simplest one from https://github.com/nix-community/pip2nix/issues/59

```
let pkgs = import <nixpkgs> { };
in                                                                         
let                                                                        
  packageOverrides = pkgs.callPackage ./python-packages.nix {};
  python = pkgs.python3.override { inherit packageOverrides; };
  pythonWithPackages = python.withPackages(ps: [ ps.fastapi ]);   
in
pkgs.mkShell {    
  buildInputs = [                       
    pythonWithPackages                       
  ];
}
```
And here is a super complex magical one https://gist.github.com/datakurre/614d6f9ee48c83bec101cd6b8cf0dbce from https://github.com/nix-community/pip2nix/issues/64

**Comment by rihardsk** [comment]
@datakurre thanks for the examples. Regrettably, the simple example is a bit too simple and the complex example seems to be a bit too complex for my needs (also i didn't manage to understand all of it) :D

But the simple example pointed me in the right direction to successfully modify my existing default.nix. Here's the commit, if you're interested https://github.com/rihardsk/mautrix-hangouts-nix/commit/f5ed572b4b56b2daff002a860b5f4e00e175ed32

Initially i tried to find a way to keep using the existing
```python
  myPythonPackages =
    (fix
    (extends pythonPackagesLocalOverrides
    (extends pythonPackagesOverrides
    (extends pythonPackagesGenerated
             basePythonPackagesUnfix))));
```
pattern but i simply couldn't get `basePythonPackagesUnfix` in the right _shape_ out of the current nixpkgs-unstable. I found that the thing that has broken the current scaffold is that at some point they stopped using `fix'` (e.g., https://github.com/NixOS/nixpkgs/blob/2e98177bd79ba132e453aae7cf9f05e6339575ec/pkgs/top-level/python-packages.nix#L7754) when constructing the python package set so an `__unfix__` attribute is no longer available. I suspect that the new approach centers around doing something similar to `fix`-ing here https://github.com/NixOS/nixpkgs/blob/6eef66f4c82d7967943ad7e453eafe003bc71858/pkgs/development/interpreters/python/default.nix#L76 but i couldn't figure out what's happening there exactly or how to extract something similar to `__unfix__` (or rather, something that doesn't introduce infinite recursion when used) out of it.

Hope this helps a bit if you do decide to update the scaffold :)

**Comment by datakurre** [comment]
@rihardsk Thanks! My personal approach (setup.nix) is different, because I aim to re-use nixpkgs package instructions, but I see that your fix is probably the correct evolution for the current pip2nix scaffold. I added issue about that.

Meanwhile, I am not familiar with mautrix-hangouts, but I am curious, if the following builds it correctly: https://gist.github.com/datakurre/4c6bf3438d015271896d7141f66bee8d

**Comment by rihardsk** [comment]
@datakurre well, it does build it, which is great. I'll have to look into what setup.nix is actually doing. Can't say if it works or not at the moment, but i'll test it out over the weekend, thanks! Btw, here's what [mautrix-hangouts](https://github.com/tulir/mautrix-hangouts) and [Matrix](https://matrix.org/) is if you want to learn more.
